/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AlphabetEntry = IDL.Record({
  'word' : IDL.Text,
  'emoji' : IDL.Text,
  'letter' : IDL.Text,
});
export const AnimalEntry = IDL.Record({
  'name' : IDL.Text,
  'emoji' : IDL.Text,
  'sound' : IDL.Text,
});
export const NumberEntry = IDL.Record({
  'value' : IDL.Nat,
  'wordLabel' : IDL.Text,
  'emoji' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'correctIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'category' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAlphabet' : IDL.Func([], [IDL.Vec(AlphabetEntry)], ['query']),
  'getAnimals' : IDL.Func([], [IDL.Vec(AnimalEntry)], ['query']),
  'getNumbers' : IDL.Func([], [IDL.Vec(NumberEntry)], ['query']),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AlphabetEntry = IDL.Record({
    'word' : IDL.Text,
    'emoji' : IDL.Text,
    'letter' : IDL.Text,
  });
  const AnimalEntry = IDL.Record({
    'name' : IDL.Text,
    'emoji' : IDL.Text,
    'sound' : IDL.Text,
  });
  const NumberEntry = IDL.Record({
    'value' : IDL.Nat,
    'wordLabel' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'correctIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'category' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAlphabet' : IDL.Func([], [IDL.Vec(AlphabetEntry)], ['query']),
    'getAnimals' : IDL.Func([], [IDL.Vec(AnimalEntry)], ['query']),
    'getNumbers' : IDL.Func([], [IDL.Vec(NumberEntry)], ['query']),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };