/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlphabetEntry {
  'word' : string,
  'emoji' : string,
  'letter' : string,
}
export interface AnimalEntry {
  'name' : string,
  'emoji' : string,
  'sound' : string,
}
export interface NumberEntry {
  'value' : bigint,
  'wordLabel' : string,
  'emoji' : string,
}
export interface QuizQuestion {
  'correctIndex' : bigint,
  'questionText' : string,
  'category' : string,
  'options' : Array<string>,
}
export interface _SERVICE {
  'getAlphabet' : ActorMethod<[], Array<AlphabetEntry>>,
  'getAnimals' : ActorMethod<[], Array<AnimalEntry>>,
  'getNumbers' : ActorMethod<[], Array<NumberEntry>>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];